import React from 'react';
import ReactDom from 'react-dom';
import Header from '../main_layout_components/header'
import CardView from '../main_layout_components/card_view'
import { Grid } from '@material-ui/core';
class MainLayout extends React.Component{
    render(){
        return(
            <div>
                <Header></Header>
                <Grid container spacing={32}>
                    <Grid item xs>    
                        <div style={{marginTop: 30}}> 
                            <CardView image="../public/stock-image.jpg" title="Company Stock" description="  
                            Company Stock displays all information regarding the stock available with us , 
                            the company target to achieve and how much stock required to complete the company target
                            of selling" button1="View Stock" button2="Learn more">
                              </CardView>
                        </div>
                    </Grid>
                    <Grid item xs>    
                        <div style={{ marginTop: 30}}> 
                            <CardView image="" title="Manage Company Target" description="  
                            Company Target helps us resolving target maintenance activity to very simpler way, this show you all the 
                            brands u have target to achieve and how much has been achieved yet with easy interface" button1="View Targets" button2="Learn more"></CardView>
                        </div>
                    </Grid>
                    <Grid item xs>    
                        <div style={{ marginTop: 30}}> 
                            <CardView image="" title="Manage Company Statistics" description="  
                            Company statistics helps a buziness improve the buying of stock , selling of stock and then 
                            company can increase the revenue of the company by observing such statistics, this provides you easy interface for working" button1="View Statistics" button2="Learn more"></CardView>
                        </div>
                    </Grid>
                    <Grid item xs>    
                        <div style={{marginTop: 30}}> 
                            <CardView image="" title="Manage Company Orders" description="  
                           Company orders can help you with maintaining the orders invoice generation and maintaining, orders are completely fetched from
                           the orders generated by the selling system, orders get synced automatically" button1="View Orders" button2="Learn more"></CardView>
                        </div>
                    </Grid>
                </Grid>
            </div>
        )
    }
}

ReactDom.render(<MainLayout/>,document.getElementById("root"));